gcc: remove empty directory
CQID: WIND00441441

Installed file libiberty.a is removed because package binutils provides it.
It may make directory empty and cause QA issue:

ERROR: QA Issue: gcc: Files/directories were installed but not shipped
  /usr/lib/armv5te

Remove the empty directory to fix it.

Signed-off-by: Kai Kang <kai.kang@windriver.com>